name: Run Test for Shop

on:
  push:
    branches: [ main , aboutFeature ]
jobs:  
  CI_Test: 
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3      
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run multiple command
      id: test_echo
      run: |
          npm install -g zcatalyst-cli 
          catalyst --version
          pwd
          catalyst project:list --token m_1004.56485c56c8720b05b1f1b8e081953fd1.d018111229fa911622f069e69ba85d24 --dc in
          
    - name: Run a one-line script  
      if: steps.test_echo.outcome == 'success'
      run: echo "result = success" >> $GITHUB_ENV      
    - name: Run a one-line script  
      if: steps.test_echo.outcome == 'failure'
      run: echo "result = success" >> $GITHUB_ENV   
    - name: Webhook
      uses: joelwmale/webhook-action@master
      with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"result": "success", "test": "t1"}'
