name: Run Test for Shop

on:
  push:
    branches: [ main , aboutFeature ]
jobs:  
  CI_Test: 
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3      
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_RESULT }}
        data: '{ "Result": "Success" }'
