name: Run Test for Shop

on:
  push:
    branches: [ main , aboutFeature ]
jobs:  
  CI_Test: 
    env:
      YESNO: Y
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3      
    - name: Run a one-line script
      run:  echo Hello, world!
    - name: Run multiple command
      run: |
          npm install -g zcatalyst-cli 
          catalyst --version
          ls -a
          pwd
          catalyst serve --token m_1004.f5a7c7290e8a2794fa49e8db88c590e0.30051397e16f7ee63c3281f52ec2468d
 
