name: Run Test for Shop

on:
  push:
    branches: [ main , aboutFeature ]
jobs:  
  CI_Test: 
    env:
      YESNO: Y
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3      
    - name: Run a one-line script
      run:  echo Hello, world!
    - name: Run multiple command
      run: |
          npm install -g zcatalyst-cli 
          catalyst --version
          catalyst init --token 1004.b9135c44c73a6554088b8a89e08814fb.6c537059be955ebdcb4dea8770d29d1f
          catalyst project:use Shop
